package edu.nuaa.nettop.dao.go;

import edu.nuaa.nettop.entity.DeployDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface DeployDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topo_position
     *
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    int insert(DeployDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topo_position
     *
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    int insertSelective(DeployDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topo_position
     *
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    DeployDO selectByPrimaryKey(Integer id);

    String queryServerIpByDeviceName(@Param("nodeName") String nodeName);

    String queryManageIpByDeviceName(@Param("nodeName") String nodeName);
}