package edu.nuaa.nettop.dao.go;

import edu.nuaa.nettop.entity.PhysicalPortDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PhysicalPortDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topo_phyvirt
     *
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    int insert(PhysicalPortDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topo_phyvirt
     *
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    int insertSelective(PhysicalPortDO record);

    List<PhysicalPortDO> findPportByWlid(@Param("wlid") String wlid);
}