package edu.nuaa.nettop.dao.go;

import edu.nuaa.nettop.entity.ServerDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ServerDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_basic
     *
     * @mbg.generated Fri Sep 18 16:30:20 CST 2020
     */
    int insert(ServerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_basic
     *
     * @mbg.generated Fri Sep 18 16:30:20 CST 2020
     */
    int insertSelective(ServerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_basic
     *
     * @mbg.generated Fri Sep 18 16:30:20 CST 2020
     */
    ServerDO selectByPrimaryKey(Integer servId);

    List<String> listServerIp();
}