package edu.nuaa.nettop.dao.main;

import edu.nuaa.nettop.entity.DDosTdDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DDosTdDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wlbs_rwcs_ddosrj
     *
     * @mbg.generated Fri Sep 18 10:17:14 CST 2020
     */
    int insert(DDosTdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wlbs_rwcs_ddosrj
     *
     * @mbg.generated Fri Sep 18 10:17:14 CST 2020
     */
    int insertSelective(DDosTdDO record);

    List<String> findTdsByRwid(@Param("rwid") String rwid);
}