package edu.nuaa.nettop.dao.main;

import edu.nuaa.nettop.entity.LinkDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface LinkDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wlbs_wlll
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    int insert(LinkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wlbs_wlll
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    int insertSelective(LinkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wlbs_wlll
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    LinkDO selectByPrimaryKey(String llid);

    List<String> findLlbsByWlid(@Param("wlid") String wlid);

    List<LinkDO> findByWlid(@Param("wlid") String wlid);
}