package edu.nuaa.nettop.dao.main;

import edu.nuaa.nettop.entity.NodeDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface NodeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wlbs_wlsb
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    int insert(NodeDO record);

    List<NodeDO> findNodeByWlid(@Param("wlid") String wlid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wlbs_wlsb
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    int insertSelective(NodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wlbs_wlsb
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    NodeDO selectByPrimaryKey(String sbid);

    String findNodeNameByPrimaryKey(@Param("sbid") String sbid);
}