package edu.nuaa.nettop.dao.main;

import edu.nuaa.nettop.entity.PhysicalDevDO;
import org.springframework.stereotype.Repository;

@Repository
public interface PhysicalDevDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wlbs_physical
     *
     * @mbg.generated Wed Sep 23 15:45:24 CST 2020
     */
    int insert(PhysicalDevDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wlbs_physical
     *
     * @mbg.generated Wed Sep 23 15:45:24 CST 2020
     */
    int insertSelective(PhysicalDevDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wlbs_physical
     *
     * @mbg.generated Wed Sep 23 15:45:24 CST 2020
     */
    PhysicalDevDO selectByPrimaryKey(String sbid);
}