package edu.nuaa.nettop.dao.main;

import edu.nuaa.nettop.entity.TaskDO;
import edu.nuaa.nettop.entity.TaskForDDosDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TaskDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wlbs_wlrw
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    int insert(TaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wlbs_wlrw
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    int insertSelective(TaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wlbs_wlrw
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    TaskDO selectByPrimaryKey(String rwid);

    TaskForDDosDO findDDosTaskByWlid(@Param("wlid") String wlid);
}