package edu.nuaa.nettop.entity;

import lombok.ToString;

@ToString
public class DDosTaskDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_rwcs_ddos.RWID
     *
     * @mbg.generated Fri Sep 18 10:17:02 CST 2020
     */
    private String rwid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_rwcs_ddos.GJDXID
     *
     * @mbg.generated Fri Sep 18 10:17:02 CST 2020
     */
    private String gjdxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_rwcs_ddos.BGJDXID
     *
     * @mbg.generated Fri Sep 18 10:17:02 CST 2020
     */
    private String bgjdxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_rwcs_ddos.GJLX
     *
     * @mbg.generated Fri Sep 18 10:17:02 CST 2020
     */
    private Short gjlx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_rwcs_ddos.RWID
     *
     * @return the value of t_wlbs_rwcs_ddos.RWID
     *
     * @mbg.generated Fri Sep 18 10:17:02 CST 2020
     */
    public String getRwid() {
        return rwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_rwcs_ddos.RWID
     *
     * @param rwid the value for t_wlbs_rwcs_ddos.RWID
     *
     * @mbg.generated Fri Sep 18 10:17:02 CST 2020
     */
    public void setRwid(String rwid) {
        this.rwid = rwid == null ? null : rwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_rwcs_ddos.GJDXID
     *
     * @return the value of t_wlbs_rwcs_ddos.GJDXID
     *
     * @mbg.generated Fri Sep 18 10:17:02 CST 2020
     */
    public String getGjdxid() {
        return gjdxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_rwcs_ddos.GJDXID
     *
     * @param gjdxid the value for t_wlbs_rwcs_ddos.GJDXID
     *
     * @mbg.generated Fri Sep 18 10:17:02 CST 2020
     */
    public void setGjdxid(String gjdxid) {
        this.gjdxid = gjdxid == null ? null : gjdxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_rwcs_ddos.BGJDXID
     *
     * @return the value of t_wlbs_rwcs_ddos.BGJDXID
     *
     * @mbg.generated Fri Sep 18 10:17:02 CST 2020
     */
    public String getBgjdxid() {
        return bgjdxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_rwcs_ddos.BGJDXID
     *
     * @param bgjdxid the value for t_wlbs_rwcs_ddos.BGJDXID
     *
     * @mbg.generated Fri Sep 18 10:17:02 CST 2020
     */
    public void setBgjdxid(String bgjdxid) {
        this.bgjdxid = bgjdxid == null ? null : bgjdxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_rwcs_ddos.GJLX
     *
     * @return the value of t_wlbs_rwcs_ddos.GJLX
     *
     * @mbg.generated Fri Sep 18 10:17:02 CST 2020
     */
    public Short getGjlx() {
        return gjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_rwcs_ddos.GJLX
     *
     * @param gjlx the value for t_wlbs_rwcs_ddos.GJLX
     *
     * @mbg.generated Fri Sep 18 10:17:02 CST 2020
     */
    public void setGjlx(Short gjlx) {
        this.gjlx = gjlx;
    }
}