package edu.nuaa.nettop.entity;

public class DDosTdDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_rwcs_ddosrj.RWID
     *
     * @mbg.generated Fri Sep 18 10:17:14 CST 2020
     */
    private String rwid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_rwcs_ddosrj.RJID
     *
     * @mbg.generated Fri Sep 18 10:17:14 CST 2020
     */
    private String rjid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_rwcs_ddosrj.RWID
     *
     * @return the value of t_wlbs_rwcs_ddosrj.RWID
     *
     * @mbg.generated Fri Sep 18 10:17:14 CST 2020
     */
    public String getRwid() {
        return rwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_rwcs_ddosrj.RWID
     *
     * @param rwid the value for t_wlbs_rwcs_ddosrj.RWID
     *
     * @mbg.generated Fri Sep 18 10:17:14 CST 2020
     */
    public void setRwid(String rwid) {
        this.rwid = rwid == null ? null : rwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_rwcs_ddosrj.RJID
     *
     * @return the value of t_wlbs_rwcs_ddosrj.RJID
     *
     * @mbg.generated Fri Sep 18 10:17:14 CST 2020
     */
    public String getRjid() {
        return rjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_rwcs_ddosrj.RJID
     *
     * @param rjid the value for t_wlbs_rwcs_ddosrj.RJID
     *
     * @mbg.generated Fri Sep 18 10:17:14 CST 2020
     */
    public void setRjid(String rjid) {
        this.rjid = rjid == null ? null : rjid.trim();
    }
}