package edu.nuaa.nettop.entity;

public class DeployDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topo_position.id
     *
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topo_position.nfvapp_id
     *
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    private Integer nfvappId;

    private ServerDO serverDO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topo_position.node_name
     *
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    private String nodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topo_position.server_id
     *
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topo_position.manage_ip
     *
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    private String manageIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topo_position.id
     *
     * @return the value of topo_position.id
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topo_position.id
     *
     * @param id the value for topo_position.id
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topo_position.nfvapp_id
     *
     * @return the value of topo_position.nfvapp_id
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    public Integer getNfvappId() {
        return nfvappId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topo_position.nfvapp_id
     *
     * @param nfvappId the value for topo_position.nfvapp_id
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    public void setNfvappId(Integer nfvappId) {
        this.nfvappId = nfvappId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topo_position.node_name
     *
     * @return the value of topo_position.node_name
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topo_position.node_name
     *
     * @param nodeName the value for topo_position.node_name
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topo_position.server_id
     *
     * @return the value of topo_position.server_id
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topo_position.server_id
     *
     * @param serverId the value for topo_position.server_id
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topo_position.manage_ip
     *
     * @return the value of topo_position.manage_ip
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    public String getManageIp() {
        return manageIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topo_position.manage_ip
     *
     * @param manageIp the value for topo_position.manage_ip
     * @mbg.generated Tue Sep 15 19:34:05 CST 2020
     */
    public void setManageIp(String manageIp) {
        this.manageIp = manageIp == null ? null : manageIp.trim();
    }
}