package edu.nuaa.nettop.entity;

import java.math.BigDecimal;
import java.util.Date;

public class LinkDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.LLID
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private String llid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.WLID
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private String wlid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.YSBID
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private String ysbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.YDK
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private String ydk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.MDSBID
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private String mdsbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.MDDK
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private String mddk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.LLBS
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private String llbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.DK
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private Integer dk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.FWSY
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private Integer fwsy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.DBL
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private BigDecimal dbl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.ZDCJF
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private Short zdcjf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.HZLX
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private String hzlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.HZFX
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private String hzfx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.GXSJ
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private Date gxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlll.LLLX
     *
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    private Short lllx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.LLID
     *
     * @return the value of t_wlbs_wlll.LLID
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public String getLlid() {
        return llid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.LLID
     *
     * @param llid the value for t_wlbs_wlll.LLID
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setLlid(String llid) {
        this.llid = llid == null ? null : llid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.WLID
     *
     * @return the value of t_wlbs_wlll.WLID
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public String getWlid() {
        return wlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.WLID
     *
     * @param wlid the value for t_wlbs_wlll.WLID
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setWlid(String wlid) {
        this.wlid = wlid == null ? null : wlid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.YSBID
     *
     * @return the value of t_wlbs_wlll.YSBID
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public String getYsbid() {
        return ysbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.YSBID
     *
     * @param ysbid the value for t_wlbs_wlll.YSBID
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setYsbid(String ysbid) {
        this.ysbid = ysbid == null ? null : ysbid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.YDK
     *
     * @return the value of t_wlbs_wlll.YDK
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public String getYdk() {
        return ydk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.YDK
     *
     * @param ydk the value for t_wlbs_wlll.YDK
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setYdk(String ydk) {
        this.ydk = ydk == null ? null : ydk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.MDSBID
     *
     * @return the value of t_wlbs_wlll.MDSBID
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public String getMdsbid() {
        return mdsbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.MDSBID
     *
     * @param mdsbid the value for t_wlbs_wlll.MDSBID
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setMdsbid(String mdsbid) {
        this.mdsbid = mdsbid == null ? null : mdsbid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.MDDK
     *
     * @return the value of t_wlbs_wlll.MDDK
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public String getMddk() {
        return mddk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.MDDK
     *
     * @param mddk the value for t_wlbs_wlll.MDDK
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setMddk(String mddk) {
        this.mddk = mddk == null ? null : mddk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.LLBS
     *
     * @return the value of t_wlbs_wlll.LLBS
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public String getLlbs() {
        return llbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.LLBS
     *
     * @param llbs the value for t_wlbs_wlll.LLBS
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setLlbs(String llbs) {
        this.llbs = llbs == null ? null : llbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.DK
     *
     * @return the value of t_wlbs_wlll.DK
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public Integer getDk() {
        return dk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.DK
     *
     * @param dk the value for t_wlbs_wlll.DK
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setDk(Integer dk) {
        this.dk = dk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.FWSY
     *
     * @return the value of t_wlbs_wlll.FWSY
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public Integer getFwsy() {
        return fwsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.FWSY
     *
     * @param fwsy the value for t_wlbs_wlll.FWSY
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setFwsy(Integer fwsy) {
        this.fwsy = fwsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.DBL
     *
     * @return the value of t_wlbs_wlll.DBL
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public BigDecimal getDbl() {
        return dbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.DBL
     *
     * @param dbl the value for t_wlbs_wlll.DBL
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setDbl(BigDecimal dbl) {
        this.dbl = dbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.ZDCJF
     *
     * @return the value of t_wlbs_wlll.ZDCJF
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public Short getZdcjf() {
        return zdcjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.ZDCJF
     *
     * @param zdcjf the value for t_wlbs_wlll.ZDCJF
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setZdcjf(Short zdcjf) {
        this.zdcjf = zdcjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.HZLX
     *
     * @return the value of t_wlbs_wlll.HZLX
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public String getHzlx() {
        return hzlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.HZLX
     *
     * @param hzlx the value for t_wlbs_wlll.HZLX
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setHzlx(String hzlx) {
        this.hzlx = hzlx == null ? null : hzlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.HZFX
     *
     * @return the value of t_wlbs_wlll.HZFX
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public String getHzfx() {
        return hzfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.HZFX
     *
     * @param hzfx the value for t_wlbs_wlll.HZFX
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setHzfx(String hzfx) {
        this.hzfx = hzfx == null ? null : hzfx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.GXSJ
     *
     * @return the value of t_wlbs_wlll.GXSJ
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.GXSJ
     *
     * @param gxsj the value for t_wlbs_wlll.GXSJ
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlll.LLLX
     *
     * @return the value of t_wlbs_wlll.LLLX
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public Short getLllx() {
        return lllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlll.LLLX
     *
     * @param lllx the value for t_wlbs_wlll.LLLX
     * @mbg.generated Tue Sep 15 19:54:18 CST 2020
     */
    public void setLllx(Short lllx) {
        this.lllx = lllx;
    }
}