package edu.nuaa.nettop.entity;

import java.math.BigDecimal;
import java.util.Date;

public class NodeDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlsb.SBID
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    private String sbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlsb.WLID
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    private String wlid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlsb.SBZL
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    private Short sbzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlsb.SBMC
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    private String sbmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlsb.SBLX
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    private String sblx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlsb.ZT
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    private Short zt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlsb.IP
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlsb.YMCD
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    private Short ymcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlsb.ZBX
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    private BigDecimal zbx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlsb.ZBY
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    private BigDecimal zby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlsb.ZDCJF
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    private Short zdcjf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlsb.GXSJ
     *
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    private Date gxsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlsb.SBID
     *
     * @return the value of t_wlbs_wlsb.SBID
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public String getSbid() {
        return sbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlsb.SBID
     *
     * @param sbid the value for t_wlbs_wlsb.SBID
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public void setSbid(String sbid) {
        this.sbid = sbid == null ? null : sbid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlsb.WLID
     *
     * @return the value of t_wlbs_wlsb.WLID
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public String getWlid() {
        return wlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlsb.WLID
     *
     * @param wlid the value for t_wlbs_wlsb.WLID
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public void setWlid(String wlid) {
        this.wlid = wlid == null ? null : wlid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlsb.SBZL
     *
     * @return the value of t_wlbs_wlsb.SBZL
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public Short getSbzl() {
        return sbzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlsb.SBZL
     *
     * @param sbzl the value for t_wlbs_wlsb.SBZL
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public void setSbzl(Short sbzl) {
        this.sbzl = sbzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlsb.SBMC
     *
     * @return the value of t_wlbs_wlsb.SBMC
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public String getSbmc() {
        return sbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlsb.SBMC
     *
     * @param sbmc the value for t_wlbs_wlsb.SBMC
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public void setSbmc(String sbmc) {
        this.sbmc = sbmc == null ? null : sbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlsb.SBLX
     *
     * @return the value of t_wlbs_wlsb.SBLX
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public String getSblx() {
        return sblx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlsb.SBLX
     *
     * @param sblx the value for t_wlbs_wlsb.SBLX
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public void setSblx(String sblx) {
        this.sblx = sblx == null ? null : sblx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlsb.ZT
     *
     * @return the value of t_wlbs_wlsb.ZT
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public Short getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlsb.ZT
     *
     * @param zt the value for t_wlbs_wlsb.ZT
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public void setZt(Short zt) {
        this.zt = zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlsb.IP
     *
     * @return the value of t_wlbs_wlsb.IP
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlsb.IP
     *
     * @param ip the value for t_wlbs_wlsb.IP
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlsb.YMCD
     *
     * @return the value of t_wlbs_wlsb.YMCD
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public Short getYmcd() {
        return ymcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlsb.YMCD
     *
     * @param ymcd the value for t_wlbs_wlsb.YMCD
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public void setYmcd(Short ymcd) {
        this.ymcd = ymcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlsb.ZBX
     *
     * @return the value of t_wlbs_wlsb.ZBX
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public BigDecimal getZbx() {
        return zbx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlsb.ZBX
     *
     * @param zbx the value for t_wlbs_wlsb.ZBX
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public void setZbx(BigDecimal zbx) {
        this.zbx = zbx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlsb.ZBY
     *
     * @return the value of t_wlbs_wlsb.ZBY
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public BigDecimal getZby() {
        return zby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlsb.ZBY
     *
     * @param zby the value for t_wlbs_wlsb.ZBY
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public void setZby(BigDecimal zby) {
        this.zby = zby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlsb.ZDCJF
     *
     * @return the value of t_wlbs_wlsb.ZDCJF
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public Short getZdcjf() {
        return zdcjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlsb.ZDCJF
     *
     * @param zdcjf the value for t_wlbs_wlsb.ZDCJF
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public void setZdcjf(Short zdcjf) {
        this.zdcjf = zdcjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_wlsb.GXSJ
     *
     * @return the value of t_wlbs_wlsb.GXSJ
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_wlsb.GXSJ
     *
     * @param gxsj the value for t_wlbs_wlsb.GXSJ
     * @mbg.generated Tue Sep 15 19:28:35 CST 2020
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }
}