package edu.nuaa.nettop.entity;

public class PhysicalDevDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_physical.SBID
     *
     * @mbg.generated Wed Sep 23 15:45:24 CST 2020
     */
    private String sbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_physical.LJSB
     *
     * @mbg.generated Wed Sep 23 15:45:24 CST 2020
     */
    private String ljsb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_physical.SBID
     *
     * @return the value of t_wlbs_physical.SBID
     * @mbg.generated Wed Sep 23 15:45:24 CST 2020
     */
    public String getSbid() {
        return sbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_physical.SBID
     *
     * @param sbid the value for t_wlbs_physical.SBID
     * @mbg.generated Wed Sep 23 15:45:24 CST 2020
     */
    public void setSbid(String sbid) {
        this.sbid = sbid == null ? null : sbid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_physical.LJSB
     *
     * @return the value of t_wlbs_physical.LJSB
     * @mbg.generated Wed Sep 23 15:45:24 CST 2020
     */
    public String getLjsb() {
        return ljsb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_physical.LJSB
     *
     * @param ljsb the value for t_wlbs_physical.LJSB
     * @mbg.generated Wed Sep 23 15:45:24 CST 2020
     */
    public void setLjsb(String ljsb) {
        this.ljsb = ljsb == null ? null : ljsb.trim();
    }
}