package edu.nuaa.nettop.entity;

public class PhysicalPortDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topo_phyvirt.vapp_id
     *
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    private Integer vappId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topo_phyvirt.vapp_name
     *
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    private String vappName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topo_phyvirt.server_ip
     *
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    private String serverIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topo_phyvirt.node_name
     *
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    private String nodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topo_phyvirt.int_name
     *
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    private String intName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topo_phyvirt.phy_int_name
     *
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    private String phyIntName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topo_phyvirt.vapp_id
     *
     * @return the value of topo_phyvirt.vapp_id
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    public Integer getVappId() {
        return vappId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topo_phyvirt.vapp_id
     *
     * @param vappId the value for topo_phyvirt.vapp_id
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    public void setVappId(Integer vappId) {
        this.vappId = vappId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topo_phyvirt.vapp_name
     *
     * @return the value of topo_phyvirt.vapp_name
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    public String getVappName() {
        return vappName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topo_phyvirt.vapp_name
     *
     * @param vappName the value for topo_phyvirt.vapp_name
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    public void setVappName(String vappName) {
        this.vappName = vappName == null ? null : vappName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topo_phyvirt.server_ip
     *
     * @return the value of topo_phyvirt.server_ip
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topo_phyvirt.server_ip
     *
     * @param serverIp the value for topo_phyvirt.server_ip
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp == null ? null : serverIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topo_phyvirt.node_name
     *
     * @return the value of topo_phyvirt.node_name
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topo_phyvirt.node_name
     *
     * @param nodeName the value for topo_phyvirt.node_name
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topo_phyvirt.int_name
     *
     * @return the value of topo_phyvirt.int_name
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    public String getIntName() {
        return intName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topo_phyvirt.int_name
     *
     * @param intName the value for topo_phyvirt.int_name
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    public void setIntName(String intName) {
        this.intName = intName == null ? null : intName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topo_phyvirt.phy_int_name
     *
     * @return the value of topo_phyvirt.phy_int_name
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    public String getPhyIntName() {
        return phyIntName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topo_phyvirt.phy_int_name
     *
     * @param phyIntName the value for topo_phyvirt.phy_int_name
     * @mbg.generated Thu Sep 24 13:00:27 GMT+08:00 2020
     */
    public void setPhyIntName(String phyIntName) {
        this.phyIntName = phyIntName == null ? null : phyIntName.trim();
    }
}