package edu.nuaa.nettop.entity;

public class ServerDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_id
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private Integer servId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_ip0
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private String servIp0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_name
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private String servName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_type
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private String servType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_os
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private String servOs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_enable
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private Byte servEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_state
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private Byte servState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_cpu
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private String servCpu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_cache
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private String servCache;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_memo
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private String servMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_power
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private String servPower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_ip
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private String servIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_port
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private String servPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_num
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private Byte servNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_sshname
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private String servSshname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_basic.serv_sshpass
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    private String servSshpass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_id
     *
     * @return the value of server_basic.serv_id
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public Integer getServId() {
        return servId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_id
     *
     * @param servId the value for server_basic.serv_id
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServId(Integer servId) {
        this.servId = servId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_ip0
     *
     * @return the value of server_basic.serv_ip0
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public String getServIp0() {
        return servIp0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_ip0
     *
     * @param servIp0 the value for server_basic.serv_ip0
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServIp0(String servIp0) {
        this.servIp0 = servIp0 == null ? null : servIp0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_name
     *
     * @return the value of server_basic.serv_name
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public String getServName() {
        return servName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_name
     *
     * @param servName the value for server_basic.serv_name
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServName(String servName) {
        this.servName = servName == null ? null : servName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_type
     *
     * @return the value of server_basic.serv_type
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public String getServType() {
        return servType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_type
     *
     * @param servType the value for server_basic.serv_type
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServType(String servType) {
        this.servType = servType == null ? null : servType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_os
     *
     * @return the value of server_basic.serv_os
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public String getServOs() {
        return servOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_os
     *
     * @param servOs the value for server_basic.serv_os
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServOs(String servOs) {
        this.servOs = servOs == null ? null : servOs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_enable
     *
     * @return the value of server_basic.serv_enable
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public Byte getServEnable() {
        return servEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_enable
     *
     * @param servEnable the value for server_basic.serv_enable
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServEnable(Byte servEnable) {
        this.servEnable = servEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_state
     *
     * @return the value of server_basic.serv_state
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public Byte getServState() {
        return servState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_state
     *
     * @param servState the value for server_basic.serv_state
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServState(Byte servState) {
        this.servState = servState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_cpu
     *
     * @return the value of server_basic.serv_cpu
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public String getServCpu() {
        return servCpu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_cpu
     *
     * @param servCpu the value for server_basic.serv_cpu
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServCpu(String servCpu) {
        this.servCpu = servCpu == null ? null : servCpu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_cache
     *
     * @return the value of server_basic.serv_cache
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public String getServCache() {
        return servCache;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_cache
     *
     * @param servCache the value for server_basic.serv_cache
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServCache(String servCache) {
        this.servCache = servCache == null ? null : servCache.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_memo
     *
     * @return the value of server_basic.serv_memo
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public String getServMemo() {
        return servMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_memo
     *
     * @param servMemo the value for server_basic.serv_memo
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServMemo(String servMemo) {
        this.servMemo = servMemo == null ? null : servMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_power
     *
     * @return the value of server_basic.serv_power
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public String getServPower() {
        return servPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_power
     *
     * @param servPower the value for server_basic.serv_power
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServPower(String servPower) {
        this.servPower = servPower == null ? null : servPower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_ip
     *
     * @return the value of server_basic.serv_ip
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public String getServIp() {
        return servIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_ip
     *
     * @param servIp the value for server_basic.serv_ip
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServIp(String servIp) {
        this.servIp = servIp == null ? null : servIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_port
     *
     * @return the value of server_basic.serv_port
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public String getServPort() {
        return servPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_port
     *
     * @param servPort the value for server_basic.serv_port
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServPort(String servPort) {
        this.servPort = servPort == null ? null : servPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_num
     *
     * @return the value of server_basic.serv_num
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public Byte getServNum() {
        return servNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_num
     *
     * @param servNum the value for server_basic.serv_num
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServNum(Byte servNum) {
        this.servNum = servNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_sshname
     *
     * @return the value of server_basic.serv_sshname
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public String getServSshname() {
        return servSshname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_sshname
     *
     * @param servSshname the value for server_basic.serv_sshname
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServSshname(String servSshname) {
        this.servSshname = servSshname == null ? null : servSshname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_basic.serv_sshpass
     *
     * @return the value of server_basic.serv_sshpass
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public String getServSshpass() {
        return servSshpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_basic.serv_sshpass
     *
     * @param servSshpass the value for server_basic.serv_sshpass
     *
     * @mbg.generated Tue Sep 15 19:34:45 CST 2020
     */
    public void setServSshpass(String servSshpass) {
        this.servSshpass = servSshpass == null ? null : servSshpass.trim();
    }
}