package edu.nuaa.nettop.entity;

import java.util.Date;

public class ServiceNetDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.WLID
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private String wlid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.FLID
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private String flid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.MBID
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private String mbid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.YXID
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private String yxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.WLMC
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private String wlmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.MBMC
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private String mbmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.ZT
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private Short zt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.DZFPFS
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private Short dzfpfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.DZFPF
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private Short dzfpf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.BZ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private String bz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.SBYY
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private String sbyy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.CJSJ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private Date cjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.CJZ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private String cjz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.GXSJ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private Date gxsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.GXZ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private String gxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_fwwl.SYBM
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    private String sybm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.WLID
     *
     * @return the value of t_wlbs_fwwl.WLID
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public String getWlid() {
        return wlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.WLID
     *
     * @param wlid the value for t_wlbs_fwwl.WLID
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setWlid(String wlid) {
        this.wlid = wlid == null ? null : wlid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.FLID
     *
     * @return the value of t_wlbs_fwwl.FLID
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public String getFlid() {
        return flid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.FLID
     *
     * @param flid the value for t_wlbs_fwwl.FLID
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setFlid(String flid) {
        this.flid = flid == null ? null : flid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.MBID
     *
     * @return the value of t_wlbs_fwwl.MBID
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public String getMbid() {
        return mbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.MBID
     *
     * @param mbid the value for t_wlbs_fwwl.MBID
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setMbid(String mbid) {
        this.mbid = mbid == null ? null : mbid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.YXID
     *
     * @return the value of t_wlbs_fwwl.YXID
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public String getYxid() {
        return yxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.YXID
     *
     * @param yxid the value for t_wlbs_fwwl.YXID
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setYxid(String yxid) {
        this.yxid = yxid == null ? null : yxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.WLMC
     *
     * @return the value of t_wlbs_fwwl.WLMC
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public String getWlmc() {
        return wlmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.WLMC
     *
     * @param wlmc the value for t_wlbs_fwwl.WLMC
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setWlmc(String wlmc) {
        this.wlmc = wlmc == null ? null : wlmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.MBMC
     *
     * @return the value of t_wlbs_fwwl.MBMC
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public String getMbmc() {
        return mbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.MBMC
     *
     * @param mbmc the value for t_wlbs_fwwl.MBMC
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setMbmc(String mbmc) {
        this.mbmc = mbmc == null ? null : mbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.ZT
     *
     * @return the value of t_wlbs_fwwl.ZT
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public Short getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.ZT
     *
     * @param zt the value for t_wlbs_fwwl.ZT
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setZt(Short zt) {
        this.zt = zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.DZFPFS
     *
     * @return the value of t_wlbs_fwwl.DZFPFS
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public Short getDzfpfs() {
        return dzfpfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.DZFPFS
     *
     * @param dzfpfs the value for t_wlbs_fwwl.DZFPFS
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setDzfpfs(Short dzfpfs) {
        this.dzfpfs = dzfpfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.DZFPF
     *
     * @return the value of t_wlbs_fwwl.DZFPF
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public Short getDzfpf() {
        return dzfpf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.DZFPF
     *
     * @param dzfpf the value for t_wlbs_fwwl.DZFPF
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setDzfpf(Short dzfpf) {
        this.dzfpf = dzfpf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.BZ
     *
     * @return the value of t_wlbs_fwwl.BZ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.BZ
     *
     * @param bz the value for t_wlbs_fwwl.BZ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.SBYY
     *
     * @return the value of t_wlbs_fwwl.SBYY
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public String getSbyy() {
        return sbyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.SBYY
     *
     * @param sbyy the value for t_wlbs_fwwl.SBYY
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setSbyy(String sbyy) {
        this.sbyy = sbyy == null ? null : sbyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.CJSJ
     *
     * @return the value of t_wlbs_fwwl.CJSJ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.CJSJ
     *
     * @param cjsj the value for t_wlbs_fwwl.CJSJ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.CJZ
     *
     * @return the value of t_wlbs_fwwl.CJZ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public String getCjz() {
        return cjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.CJZ
     *
     * @param cjz the value for t_wlbs_fwwl.CJZ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setCjz(String cjz) {
        this.cjz = cjz == null ? null : cjz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.GXSJ
     *
     * @return the value of t_wlbs_fwwl.GXSJ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public Date getGxsj() {
        return gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.GXSJ
     *
     * @param gxsj the value for t_wlbs_fwwl.GXSJ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setGxsj(Date gxsj) {
        this.gxsj = gxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.GXZ
     *
     * @return the value of t_wlbs_fwwl.GXZ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public String getGxz() {
        return gxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.GXZ
     *
     * @param gxz the value for t_wlbs_fwwl.GXZ
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setGxz(String gxz) {
        this.gxz = gxz == null ? null : gxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wlbs_fwwl.SYBM
     *
     * @return the value of t_wlbs_fwwl.SYBM
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public String getSybm() {
        return sybm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wlbs_fwwl.SYBM
     *
     * @param sybm the value for t_wlbs_fwwl.SYBM
     *
     * @mbg.generated Tue Sep 15 19:15:23 CST 2020
     */
    public void setSybm(String sybm) {
        this.sybm = sybm == null ? null : sybm.trim();
    }
}