package edu.nuaa.nettop.entity;

import lombok.Data;

import java.util.List;

@Data
public class TaskDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlrw.RWID
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    private String rwid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlrw.WLID
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    private String wlid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlrw.RWLX
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    private String rwlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlrw.KSSJ
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    private Integer kssj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlrw.YZYXF
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    private Short yzyxf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlrw.ZQZXF
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    private Short zqzxf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlrw.ZXJG
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    private Short zxjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlrw.RWMS
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    private String rwms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlrw.ZT
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    private Short zt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlrw.JSSJ
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    private Integer jssj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlrw.ZXSC
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    private Integer zxsc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wlbs_wlrw.RWMC
     *
     * @mbg.generated Fri Sep 18 10:16:20 CST 2020
     */
    private String rwmc;
}