server:
  port: 9999

web:
  ip: 192.168.31.183
  port: 8080
  redis:
    host: 192.168.31.15
    port: 6379
    password: 123456

spring:
  datasource:
    nettop:
      jdbc-url: jdbc:mysql://192.168.31.13:3306/nettop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: welcome
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
    go:
      jdbc-url: jdbc:mysql://192.168.31.13:3306/nettopd_go?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: welcome
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5

mybatis:
  mapper-locations: classpath:mapping/*.xml

logging:
  level:
    ROOT: INFO
    org.springframework.web: ERROR
    com.ibatis: debug
    com.cetccity: info

quartz:
  scheduler:
    instance-name: MonitorScheduler
    instance-id: AUTO
    skip-update-check: true
    job-factory:
      class: org.quartz.simpl.SimpleJobFactory
  job-store:
    class: org.quartz.impl.jdbcjobstore.JobStoreTX
    driver-delegate-class: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
    datasource: quartzDataSource
    table-prefix: QRTZ_
    is-clustered: false
  thread-pool:
    class: org.quartz.simpl.SimpleThreadPool
    thread-count: 30
  datasource:
    quartzDataSource:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.31.13:3306/monitor_job?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
      user: root
      password: welcome
      maxConnections: 5
      validationQuery: select 0
      connection-provider: edu.nuaa.nettop.quartz.DruidConnectionProvider